spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:9002
          predicates:
            - Path=/api/**
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456@Aa
    database: 0
server:
  port: 9000
  servlet:
    context-path: /api
com:
  which:
    client:
      # gateway host（仅用于 dev环境）
      host: http://localhost:9000
dubbo:
  application:
    name: dubbo-springboot-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848