spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:9002
          predicates:
            - Path=/api/**
server:
  address: 0.0.0.0
  port: 9000
  servlet:
    context-path: /api
dubbo:
  application:
    name: dubbo-springboot-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848