spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8002
          predicates:
            - Path=/api/**
server:
  address: 0.0.0.0
  port: 8000
  servlet:
    context-path: /api