# 公共配置文件
# @author which
spring:
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # session 配置
  session:
    # 30 天过期
    timeout: 2592000
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://freefish.love:3306/api_platform
    username: api_platform
    password: AEh5xER6r2WW4csc
  redis:
    host: freefish.love
    port: 6379
    password: 123456@Aa
    database: 0
server:
  port: 9001
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
dubbo:
  application:
    name: dubbo-springboot-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://freefish.love:8848
    username: nacos
    password: 123456@Aa
# 对象存储 oss
alibaba:
  cloud:
    oss:
      endpoint: https://oss-cn-beijing.aliyuncs.com
    access-key: LTAI5tM9SCZnTtQoyZZFSZZU
    secret-key: iQK0CFotGSqyLPCWIuqxdI0HE5nBIF
